config/routes.rb
Trendy::Application.routes.draw do
  get "users/new"

  root 'posts#index'

  get '/posts' => 'posts#index'
  get '/posts/category/:id' => 'posts#category'
  get 'posts/search/' => 'posts#search', as: 'posts_search'

  get 'users/login' => 'sessions#new'
  get 'users/logout' => 'sessions#destroy', as: 'log_out'
  get 'user/settings' => 'customizes#edit', as: 'settings_edit'
  post 'user/settings' => 'customizes#create', as: 'settings'
  resources :users
  resources :sessions, only: [:create, :destroy]

  resources :shares , only: [:create]

  resources :rates, only: [:create]

  get '404', :to => 'application#page_not_found'
  get '422', :to => 'application#server_error'
  get '500', :to => 'application#server_error'

end

app/controllers/customizes_controller.rb
#!/bin/env ruby
# encoding: utf-8

class CustomizesController < ApplicationController

  def edit
    @customizes = Customize.includes(:category).where(user_id: session[:user_id])
    @categories = Category.all
  end

  def create
    $state = true;
    c = Category.all
    Customize.transaction do
      c.each do |category|
        if params[category.id.to_s] then
          if Customize.where(category_id: category.id, user_id: session[:user_id]).exists? then
            c = Customize.where(category_id: category.id, user_id: session[:user_id]).first
            unless Customize.update(c.id, rank: params[category.id.to_s]) then
              $state = false
              redirect_to settings_edit_path, alert: 'Error al actualizar las opciones del usuario.'
              raise ActiveRecord::Rollback
            end
          else

            c = Customize.create category_id: category.id, user_id: session[:user_id], rank: params[category.id.to_s]
            unless c.save then
              $state = false
              redirect_to settings_edit_path, alert: 'Error al crear las opciones del usuario.'
              raise ActiveRecord::Rollback
            end
          end
        else
          $state = false
          redirect_to settings_edit_path, alert: 'Error de parámetros.'
          raise ActiveRecord::Rollback
        end
      end
    end
    redirect_to settings_edit_path, notice: 'Opciones actualizadas correctamente.' if $state
  end
end

app/helpers/customizes_helper.rb
module CustomizesHelper
end

app/views/customizes/edit.html.erb
<% if @current_user then %>
    <% content_for :head do %>
        <%= javascript_include_tag 'customizes' %>
        <%= javascript_include_tag 'rangeslider.min' %>
        <%= stylesheet_link_tag 'rangeslider' %>
    <% end %>

    <%= content_for :head %>
    <!-- Main Wrapper -->
    <div id="main-wrapper">
      <div class="container">
        <div class="row">
          <div class="12u skel-cell-important">

            <!-- Content -->
            <div id="content">
              <h3 style="margin-bottom: 0.5em">Elige tus preferencias sobre cada categoría</h3>
              <span>Puntua de 1 a 10 el grado de interés que tiene por cada categoría.</span><br><br>
              <%=	form_tag settings_path do  %>
                  <% unless @customizes.count == 0 then %>
                      <% @customizes.each do |customize| %>
                      <p>
                        <span><%= customize.category.name %> </span> <%= range_field_tag customize.category.id, customize.rank, {min:0, max: 10, step: 1} %>
                      </p>
                      <% end %>
                  <% else %>
                      <% @categories.each do |category| %>
                          <p>
                            <span><%= category.name %> </span> <%= range_field_tag category.id, '0', {min:0, max: 10, step: 1} %>
                          </p>
                      <% end %>
                  <% end %>
                  <%= submit_tag 'Guardar', class: 'button small' %>
              <% end %>
            </div>

          </div>
        </div>
      </div>
    </div>
<% else %>
    <h1>Necesitas estár autenticado para ver esto.</h1>
<% end %>