config/routes.rb
Trendy::Application.routes.draw do
  get "users/new"

  root 'posts#index'

  get '/posts' => 'posts#index'
  get '/posts/category/:id' => 'posts#category'
  get 'posts/search/' => 'posts#search', as: 'posts_search'

  get 'users/login' => 'sessions#new'
  get 'users/logout' => 'sessions#destroy', as: 'log_out'
  get 'user/settings' => 'customizes#edit', as: 'settings_edit'
  post 'user/settings' => 'customizes#create', as: 'settings'
  resources :users
  resources :sessions, only: [:create, :destroy]

  resources :shares , only: [:create]

  resources :rates, only: [:create]

  get '404', :to => 'application#page_not_found'
  get '422', :to => 'application#server_error'
  get '500', :to => 'application#server_error'

end

app/views/layouts/application.html.erb
<!DOCTYPE HTML>
<html>
<head>
  <title>Trendy</title>
  <meta http-equiv="content-type" content="text/html; charset=utf-8" />
  <meta name="description" content="" />
  <meta name="keywords" content="" />
  <%= stylesheet_link_tag "http://fonts.googleapis.com/css?family=Open+Sans:300,800" %>
  <%= stylesheet_link_tag "http://fonts.googleapis.com/css?family=Oleo+Script:400" %>
  <%= stylesheet_link_tag "pagination" %>
  <%= javascript_include_tag "jquery.min" %>
  <%= javascript_include_tag "config" %>
  <%= javascript_include_tag "skel.min" %>
  <%= javascript_include_tag "skel-panels.min" %>
  <%= javascript_include_tag "rate" %>
  <!-- Only for JQuery dropdown -->
  <%= stylesheet_link_tag "jquery.dropdown" %>
  <%= javascript_include_tag "jquery.dropdown.min" %>
  <%= javascript_include_tag "shares" %>
  <!-- -->

  <%= yield :head %>

  <noscript>
    <%= stylesheet_link_tag "skel-noscript" %>
    <%= stylesheet_link_tag "style" %>
    <%= stylesheet_link_tag "style-desktop" %>
  </noscript>
  <!--[if lte IE 8]><%= javascript_include_tag "html5shiv" %> <%= stylesheet_link_tag "ie8" %><![endif]-->
  <!--[if lte IE 7]><%= stylesheet_link_tag "ie7" %><![endif]-->
  <%= csrf_meta_tags %>
</head>
<body class="homepage">

<!-- Header Wrapper -->
<div id="header-wrapper">
  <div class="container">
    <div class="row">
      <div class="12u">

        <!-- Header -->
        <header id="header">

          <!-- Logo -->
          <div id="logo">
            <h1><a href="/" id="logo">Trendy</a></h1>
            <span>Lo interesante está aquí...</span>
          </div>

          <!-- Nav -->
          <nav id="nav">
            <ul>
              <% if @current_page.nil? then %>
                  <li class="current_page_item"><a href="#">Principal</a></li>
              <% else %>
                  <% @categories.each do |category| %>
                      <% if @current_page.to_i == category.id.to_i %>
                          <li class="current_page_item"><a href="#"><%= category.name %></a></li>
                      <% end %>
                  <% end %>
              <% end %>
              <% if @current_user then %>
                  <li><%= link_to "#{@current_user.username}(logout)", log_out_path %></li>
                  <li><%= link_to 'Ajustes', settings_edit_path %></li>
              <% else %>
              <li><a href="/users/login" data-dropdown="#dropdown-3">Autenticate</a></li>
              <% end %>
              <li><a href="#" data-dropdown="#dropdown-1">Categorias</a>
                <ul hidden="hidden">
                  <% @categories.each do |category| %>
                      <li><%=link_to "&nbsp;&nbsp;&nbsp;&nbsp;#{category.name}", "/posts/category/#{category.id}" %></li>
                  <% end %>
                </ul>
              </li>
              <li><a href="/posts/search" data-dropdown="#dropdown-2">Buscar</a></li>
            </ul>
          </nav>
        </header>
        <div id="dropdown-1" class="dropdown dropdown-tip">
          <ul class="dropdown-menu">
            <% @categories.each do |category| %>
                <li><%=link_to "#{category.name}", "/posts/category/#{category.id}" %></li>
            <% end %>
          </ul>
        </div>
        <div id="dropdown-2" class="dropdown dropdown-tip">
          <div class="dropdown-panel">
            <%= form_tag posts_search_path, method: 'get' do %>
                <%= text_field_tag :query, params[:query], style: 'display: inline-block', placeholder: 'Buscar' %>
            <% end %>
          </div>
        </div>
        <div id="dropdown-3" class="dropdown dropdown-tip">
          <div class="dropdown-panel">
            <%= form_tag sessions_path do %>
                <%= text_field_tag :username, params[:username], placeholder: 'Usuario' %>
                <%= password_field_tag :password, params[:password], placeholder: 'Contraseña' %>
                <%= submit_tag 'Enviar', class: 'button small' %>
                <button type="button" class="button small" onclick="window.location.href='/users/new'">Registrate!</button>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<!-- Error messagges -->
<div id="message-box">
  <div class="container">
    <div class="row">
      <div class="12u">
        <% flash.each do |name, msg| %>
            <div class="message <%= name == :notice ? 'success' : 'error' %>">
              <%= msg %>
            </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

<%= yield %>

<!-- Footer Wrapper -->
<div id="footer-wrapper">
  <footer id="footer" class="container">
    <div class="row">
      <div class="12u">
        <div id="copyright">
          &copy; Trendy. All rights reserved. | Sergio Cancelo </a>
        </div>
      </div>
    </div>
  </footer>
</div>

</body>
</html>